name: Deploy Frontend to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Setup Pages
        uses: actions/configure-pages@v3
        
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      
      - name: Get Elastic Beanstalk URL
        id: get-eb-url
        run: |
          EB_URL=$(aws elasticbeanstalk describe-environments --environment-names aushadhi-production --query "Environments[0].CNAME" --output text || echo "aushadhi-production.us-east-1.elasticbeanstalk.com")
          echo "eb_url=$EB_URL" >> $GITHUB_OUTPUT
          echo "Using Elastic Beanstalk URL: $EB_URL"
      
      - name: Update API URL for production
        run: |
          # Replace the API_URL with the AWS Elastic Beanstalk production URL
          # Use https instead of http for secure connections
          if grep -q "const API_URL" script.js; then
            sed -i 's|const API_URL = .*|const API_URL = "https://${{ steps.get-eb-url.outputs.eb_url }}";|g' script.js
          fi
          
          if grep -q "const API_URL" index.html; then
            sed -i 's|const API_URL = .*|const API_URL = "https://${{ steps.get-eb-url.outputs.eb_url }}";|g' index.html
          fi
          
          if grep -q "const API_URL" demo.html; then
            sed -i 's|const API_URL = .*|const API_URL = "https://${{ steps.get-eb-url.outputs.eb_url }}";|g' demo.html
          fi
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: '.'
          
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
